all: backtrack.c bruteForce.c dynamic.c huffman.c
	gcc backtrack.c -o backtrack.out
	gcc bruteForce.c -o bruteForce.out -lm
	gcc dynamic.c -o dynamic.out -lm
	gcc huffman.c -o huffman.out
	
clean:
	rm -rf backtrack.out bruteForce.out dynamic.out huffman.out